export const GET_APP_DETAILS = "GET_APP_DETAILS";
export const GET_APP_DETAILS_LOADING = "GET_APP_DETAILS_LOADING";
export const GET_APP_DETAILS_FAILED = "GET_APP_DETAILS_FAILED";

//classes
//Get class
export const GET_CLASSES = "GET_CLASSES";
export const GET_CLASSES_LOADING = "GET_CLASSES_LOADING";
export const GET_CLASSES_FAILED = "GET_CLASSES_FAILED";

//Add class
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_LOADING = "ADD_CLASS_LOADING";
export const ADD_CLASS_FAILED = "ADD_CLASS_FAILED";
export const ADD_CLASS_CLEAR_MESSAGE = "ADD_CLASS_CLEAR_MESSAGE";

//Add student
export const ADD_STUDENT_LOADING = "ADD_STUDENT_LOADING";
export const ADD_STUDENT_FAILED = "ADD_STUDENT_FAILED";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_CLEAR_MESSAGE = "ADD_STUDENT_CLEAR_MESSAGE";

//Get student
export const GET_STUDENTS_LOADING = "GET_STUDENTS_LOADING";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_FAILED = "GET_STUDENTS_FAILED";
export const GET_STUDENTS_CLEAR_MESSAGE = "GET_STUDENTS_CLEAR_MESSAGE";

//Mark attendance
export const MARK_ATTENDANCE_LOADING = "MARK_ATTENDANCE_LOADING";
export const MARK_ATTENDANCE_SUCCESS = "MARK_ATTENDANCE_SUCCESS";
export const MARK_ATTENDANCE_FAILED = "MARK_ATTENDANCE_FAILED";
export const MARK_ATTENDANCE_CLEAR = "MARK_ATTENDANCE_CLEAR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGGED_IN_STATE = "LOGGED_IN_STATE";
export const LOGOUT_SUCCESS = "LOGOUT";

//Recaptcha
export const RECAPTCHA_SELECTED = "RECAPTCHA_SELECTED";
export const CLEAR_RECAPTCHA = "CLEAR_RECAPTCHA";
